// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.44
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace LineUp
{
    internal sealed partial class Vsix
    {
        public const string Id = "LineUp.ddb701d6-4b7d-41e7-a011-c1f2a7c36d17";
        public const string Name = "Line Up";
        public const string Description = @"A simple code rearrangement tool.A";
        public const string Language = "en-US";
        public const string Version = "1.0.2";
        public const string Author = "Olumuyiwa Agboola";
        public const string Tags = "";
        public const bool IsPreview = false;
    }
}
