// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace LineUp
{
    internal sealed partial class Vsix
    {
        public const string Id = "LineUp.ddb701d6-4b7d-41e7-a011-c1f2a7c36d17";
        public const string Name = "LineUp";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Olumuyiwa Agboola";
        public const string Tags = "";
    }
}
